n = input("Digite algo: ")
print("O tipo primitivo desse valor é: {}".format(type(n)))
print("Só tem espaços? {}".format(n.isspace()))
print("É um número? {}".format(n.isnumeric()))
print("É alfabetico? {}".format(n.isalpha()))
print("É alfanumérico? {}".format(n.isalnum()))
print("Está em maiúsculas? {}".format(n.isupper()))
print("Está em minúsculas? {}".format(n.islower()))
print("Está em capitalizada? {}".format(n.istitle()))
